//INVITE
export const GET_INVITE_REQUESTED = 'GET_INVITE_REQUESTED';
export const GET_INVITE_REJECTED = 'GET_INVITE_REJECTED';
export const GET_INVITE_FULFILLED = 'GET_INVITE_FULFILLED';

//USER
export const SIGN_IN = 'SIGN_IN ';
export const SIGN_IN_SUCCESS= 'SIGN_IN_USER_SUCCESS';
export const SIGN_IN_ERROR= 'SIGN_IN_USER_ERROR';
export const SIGN_OUT = 'SIGN_OUT_USER';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

//NEWS
export const ADD_NEWS ='ADD_NEWS';
export const ADD_NEWS_SUCCESS = 'ADD_NEWS_SUCCESS';
export const DELETE_NEWS ='DELETE_NEWS';
export const DELETE_NEWS_SUCCESS = 'DELETE_NEWS_SUCCESS';
export const GET_NEWS ='GET_NEWS';
export const GET_NEWS_SUCCESS ='GET_NEWS_SUCCESS';
export const SET_ACTIVE_NEWS = 'SET_ACTIVE_NEWS';

//APP
export const PERFORM_REQUEST = 'PERFORM_REQUEST';